version: '3'
services:
  app:
    container_name: vending-app
    restart: always
    build: .
    environment: 
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
volumes:
  data:
